services:
  postgres:
    image: gui2310g/postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guilherme10!
      POSTGRES_DB: gerenciamentotarefas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build: .
    image: gui2310g/api-gerenciamentotarefas
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gerenciamentotarefas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: guilherme10!
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - my-network

  pgadmin:
    image: gui2310g/pgadmin
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
